name: tourist_safety_app
description: Smart Tourist Safety Monitoring System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
    

  # Blockchain dependencies
  web3dart: ^2.7.3
  geofence_service: ^6.0.0+1 
  http: ^1.1.0
  flutter_dotenv: ^6.0.0
  porcupine_flutter: ^3.0.5
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # Crypto and security
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # HEX decoder (used for hex.decode)
  convert: ^3.0.1

  # State management
  provider: ^6.1.1

  # UI dependencies
  cupertino_icons: ^1.0.6

  # Storage
  shared_preferences: ^2.2.2

  # QR Code
  qr_flutter: ^4.1.0

  # Permission handling
  permission_handler: ^12.0.1

  # Location services
  geolocator: ^14.0.2

  # Notifications
  flutter_local_notifications: ^19.4.1

  # ✅ Google Maps (replacing flutter_map for better API integration)
  google_maps_flutter: ^2.5.0
  
  # ✅ Keep latlong2 for coordinate calculations
  latlong2: ^0.9.1

  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  url_launcher: ^6.3.0
  flutter_phone_direct_caller: ^2.1.1
  # Google Sign-In
  google_sign_in: ^6.2.1
  # Health (Health Connect / HealthKit)
  health: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/contracts/
    - assets/wakewords/hey_sentry.ppn
    - .env