name: tourist_safety_app
description: Smart Tourist Safety Monitoring System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Blockchain dependencies
  web3dart: ^2.7.3
  geofence_service: ^6.0.0+1 
  http: ^1.1.0

  # Crypto and security
  crypto: ^3.0.3
  pointycastle: ^3.7.3

  # HEX decoder (used for hex.decode)
  convert: ^3.0.1

  # State management
  provider: ^6.1.1

  # UI dependencies
  cupertino_icons: ^1.0.6

  # Storage
  shared_preferences: ^2.2.2

  # QR Code
  qr_flutter: ^4.1.0

  # Permission handling
  permission_handler: ^11.1.0

  # Location services
  geolocator: ^10.1.0

  # Notifications
  flutter_local_notifications: ^19.4.1

  # ✅ Google Maps (replacing flutter_map for better API integration)
  google_maps_flutter: ^2.5.0
  
  # ✅ Keep latlong2 for coordinate calculations
  latlong2: ^0.9.1

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/contracts/