// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2PnpKfvHeM5XMIvwuUSh-kxGOdFRloXU',
    appId: '1:514911857172:web:364fe3318ff52583c29501',
    messagingSenderId: '514911857172',
    projectId: 'touristapp-2941f',
    authDomain: 'touristapp-2941f.firebaseapp.com',
    storageBucket: 'touristapp-2941f.firebasestorage.app',
    measurementId: 'G-TMYXJE2ZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiDTmIZLbskVu2g_BG1hy2jsWt97UXFNg',
    appId: '1:514911857172:android:590a639bee0888bac29501',
    messagingSenderId: '514911857172',
    projectId: 'touristapp-2941f',
    storageBucket: 'touristapp-2941f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0pZQB6sl20vgwYCczn7K7PnHxaeIEDA',
    appId: '1:514911857172:ios:d83942531b3f63ebc29501',
    messagingSenderId: '514911857172',
    projectId: 'touristapp-2941f',
    storageBucket: 'touristapp-2941f.firebasestorage.app',
    iosBundleId: 'com.example.touristapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0pZQB6sl20vgwYCczn7K7PnHxaeIEDA',
    appId: '1:514911857172:ios:d83942531b3f63ebc29501',
    messagingSenderId: '514911857172',
    projectId: 'touristapp-2941f',
    storageBucket: 'touristapp-2941f.firebasestorage.app',
    iosBundleId: 'com.example.touristapp',
  );
}
